# generated by datamodel-codegen:
#   filename:  citation.schema.json
#   timestamp: 2023-07-19T19:28:43+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Extra


class Citation(BaseModel):
    class Config:
        extra = Extra.allow

    cite_as: Optional[str] = None
    doi: Optional[str] = None


class Model(BaseModel):
    __root__: Citation
