# generated by datamodel-codegen:
#   filename:  contact_info.schema.json
#   timestamp: 2023-07-19T19:28:42+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Extra


class ContactInfo(BaseModel):
    class Config:
        extra = Extra.allow

    contact: Optional[str] = None
    organization: Optional[str] = None


class Model(BaseModel):
    __root__: ContactInfo
