# generated by datamodel-codegen:
#   filename:  uuid.schema.json
#   timestamp: 2023-07-19T19:28:42+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Extra


class UUID(BaseModel):
    class Config:
        extra = Extra.allow

    value: Optional[str] = None


class Model(BaseModel):
    __root__: UUID
