# generated by datamodel-codegen:
#   filename:  dataset.schema.json
#   timestamp: 2023-07-19T19:28:43+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Extra, Field

from . import odp


class DatasetSpec(BaseModel):
    class Config:
        extra = Extra.allow

    storage_class: str = Field(
        ..., description="The storage class qualified name of the dataset"
    )
    storage_controller: Optional[str] = Field(
        None, description="Storage controller qualified name"
    )
    data_collection: Optional[str] = Field(
        None, description="Data collection qualified name"
    )
    maintainer: odp.ContactInfo = Field(
        ..., description="Active maintainer contact information"
    )
    citation: Optional[odp.Citation] = Field(
        None, description="Information on how to cite the dataset"
    )
    documentation: Optional[List[str]] = Field(
        None, description="Links to any relevant documentation"
    )
    attributes: Optional[List[odp.Attribute]] = Field(
        None, description="Dataset attributes"
    )
    tags: Optional[List[str]] = Field(
        None, description="Dataset tags to aid with search and discovery"
    )


class Model(BaseModel):
    __root__: DatasetSpec
