# generated by datamodel-codegen:
#   filename:  resource_status.schema.json
#   timestamp: 2023-07-19T19:28:41+00:00

from __future__ import annotations

from datetime import datetime
from typing import Optional

from pydantic import BaseModel, Extra

from . import odp


class ResourceStatus(BaseModel):
    class Config:
        extra = Extra.allow

    num_updates: Optional[str] = None
    created_time: Optional[datetime] = None
    created_by: Optional[odp.UUID] = None
    updated_time: Optional[datetime] = None
    updated_by: Optional[odp.UUID] = None
    deleted_time: Optional[datetime] = None
    deleted_by: Optional[odp.UUID] = None


class Model(BaseModel):
    __root__: ResourceStatus
